name: nix-runner
services:
  nix-runner:
    build: .
    volumes:
      - ./backup:/backup
    environment:
      - ORG_TOKEN=${ORG_TOKEN}
      - REPO_TOKEN=${REPO_TOKEN}
      - GITEA_TOKEN=${GITEA_TOKEN}
    command: ["https://github.com/spotdemo4/nix-flake-release"]
    restart: no
    stop_grace_period: 30s
