name: nix-runner
services:
  nix-runner:
    build: .
    volumes:
      - ./backup:/backup
    environment:
      - ORG_TOKEN=${ORG_TOKEN}
      - REPO_TOKEN=${REPO_TOKEN}
    command: ["trevllc", "spotdemo4/go-template"]
    restart: no
    stop_grace_period: 30s
