name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "Force"
        required: false
        type: choice
        default: "true"
        options:
          - "true"
          - "false"

concurrency:
  group: release

permissions:
  contents: read

jobs:
  bump:
    runs-on: nix
    steps:
      - name: Checkout
        uses: spotdemo4/better-checkout@b5c8c788dc5653b255e55658e8c2910b62c5f13b # v0.4.0
        with:
          app-id: ${{ vars.RENOVATE_ID }}
          private-key: ${{ secrets.RENOVATE_KEY }}
          shell: bump

      - name: Bump
        run: bumper
        env:
          FORCE: ${{ inputs.force }}
          PATHS: |-
            .github/README.md
