name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "Force"
        required: false
        type: choice
        default: "true"
        options:
          - "true"
          - "false"

concurrency:
  group: release

permissions:
  contents: read

jobs:
  bump:
    runs-on: nix
    steps:
      - name: Checkout
        uses: spotdemo4/better-checkout@47df133e9f043cd08660fed5a09b6c20232ce909 # v0.2.0
        with:
          app-id: ${{ vars.RENOVATE_ID }}
          private-key: ${{ secrets.RENOVATE_KEY }}

      - name: Nix develop
        uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
        with:
          arguments: ".#bump"

      - name: Bump
        run: bumper
        env:
          FORCE: ${{ inputs.force }}
          PATHS: |-
            .github/README.md
